name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest

          - name: Deploy to remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_IP }}  # L'adresse IP ou le nom de domaine du serveur distant
        username: ${{ secrets.DEPLOYMENT_USER }}  # Le nom d'utilisateur SSH pour se connecter au serveur distant
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}  # La clé privée SSH pour l'authentification
        passphrase: ${{ secrets.DEPLOYMENT_SSH_PASSPHRASE }}  # La passphrase de la clé privée SSH
        script: |
          echo "Deploying Docker image to remote server..."
          docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest
          docker stop my-container || true
          docker rm my-container || true
          docker run -d --name my-container -p 8022:8022 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest
