name: CI and Deployment Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Premier job: Construction de l'image Docker
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_API_KEY }}
          registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
          
      - name: Build Docker image
        run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest
      
      - name: Push Docker image
        run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest

  # Deuxième job: Déploiement sur le serveur distant
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job "build"
    steps:
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DEPLOYMENT_SERVER_IP }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          script: |
            echo "Deploying Docker image to remote server..."
            docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest
            docker stop jo-container || true
            docker rm jo-container || true
            docker run -d --name jo-container -p 8022:8022 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/jojo:latest
